### PR TITLE
Email confirmation

### PR DESCRIPTION
**Pull request by aquilarafa**
- [x] Add confirmed_at:datetime to Subscriber
- [x] Add new mailer SubcriberMailer?
- [x] Send a link to confirm using signed global id(subscriber.to_sgid.to_s)
- [x] Update confirmed_at when link is clicked
- [x] Setup production email delivery using Postmark

### CODE REVIEW

**Comment by aquilarafa** [comment]
Steps to configure Postmark API token:

Save your Postmark Server API Token to [config/credentials.yml.enc](https://guides.rubyonrails.org/security.html#custom-credentials):

run `rails secret`, then run `rails credentials:edit` and add:

```yaml
postmark_api_token: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
```

**Review by gathuku — COMMENTED** [review]
This looks good @aquilarafa 
One thing i would like to change is adding a new controller for confirmation . Maybe something like `subcriber_confirmations`, This way each controller will remain with only RESTful actions ie index,new,create etc

So the routes will be something like 

```
  resources :subscribers, only: [:create] do
    resource :confirm, only: [:create], controller: :subsbriber_confirmations
```
The idea of adding a new 'EmailConfirmationToken' is cool, I think it can be used to track the number of confirmations sent.

**Comment by aquilarafa** [comment]
> ```ruby
> resource :confirm, only: [:create], controller: :subsbriber_confirmations
> ```

Yes. This was my initial idea! Done. 
But I kept the same URL pattern for confirmations: GET /subscribers/confirmations?sid=...

**Comment by gathuku** [comment]
Nice @aquilarafa , I don't want to request alot of changes 😄 . But if you still have time you can look at test the mailer. Wrote a blog https://gathuku.me/2019/12/15/testing-action-mailer-rails.html sometime later, Am not sure if it's still applicable.

**Comment by aquilarafa** [comment]
> Nice @aquilarafa , I don't want to request alot of changes 😄 . But if you still have time you can look at test the mailer. Wrote a blog https://gathuku.me/2019/12/15/testing-action-mailer-rails.html sometime later, Am not sure if it's still applicable.

No problem. Can help with that. 

Would you style them later?

**Comment by gathuku** [comment]
> > Nice @aquilarafa , I don't want to request alot of changes 😄 . But if you still have time you can look at test the mailer. Wrote a blog https://gathuku.me/2019/12/15/testing-action-mailer-rails.html sometime later, Am not sure if it's still applicable.
> 
> No problem. Can help with that.
> 
> Would you style them later?

@aquilarafa Am okay with plain text email.

**Comment by gathuku** [comment]
> > @aquilarafa Tried to keep it simple at first and see how it goes, Please check if I missed something.
> 
> No problem. Looks good to me. 👍
> 
> One thing only. I don't like to expose the subscriber ID in the url path `/subscribers/:subscriber_id/confirmation`
> 
> But if it is not a problem for now. Nervermind.

@aquilarafa Sure, it won't be exactly an integer id. It's the signed id 
example

```
http://localhost:3000/subscribers/BAh7CEkiCGdpZAY6BkVUSSI6Z2lkOi8vaG90d2lyZWRleGFtcGxlcy9TdWJzY3JpYmVyLzE_ZXhwaXJlc19pbj0xNzI4MDAGOwBUSSIMcHVycG9zZQY7AFRJIgxkZWZhdWx0BjsAVEkiD2V4cGlyZXNfYXQGOwBUSSIdMjAyMy0wNi0xNVQxNjozMzozNi4zNzBaBjsAVA==--a3f58e572882093f5debcf14ced8f4900b00afa8/confirmation
```

**Pull request merged**
